In [ ]:
#  Clean and explore the dataset in Python.
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("sample_data_week-4.xlsx")

In [ ]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Germany,Carretera,NaN,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
1,Government,Germany,Paseo,NaN,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014
2,Government,Canada,Paseo,NaN,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013
3,Government,Germany,Paseo,NaN,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014
4,Government,Germany,Velo,NaN,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014

In [ ]:
df.shape

(700, 16)

In [ ]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='object')

In [ ]:
df.dtypes

Segment                        object
Country                        object
Product                        object
Discount Band                  object
Units Sold                    float64
Manufacturing Price             int64
Sale Price                      int64
Gross Sales                   float64
Discounts                     float64
Sales                         float64
COGS                          float64
Profit                        float64
Date                   datetime64[ns]
Month Number                    int64
Month Name                     object
Year                            int64
dtype: object

In [ ]:
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
Sales                   0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [ ]:
df['Discount Band'] = df['Discount Band'].fillna('Unknown')

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [ ]:
df['Date'].dtype

dtype('<M8[ns]')

In [ ]:
df.describe()

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.000000,700.000000,700.000000,7.000000e+02,700.000000,7.000000e+02,700.000000,700.000000,700,700.000000,700.000000
mean,1608.294286,96.477143,118.428571,1.827594e+05,13150.354629,1.696091e+05,145475.211429,24133.860371,2014-04-28 21:36:00,7.900000,2013.750000
min,200.000000,3.000000,7.000000,1.799000e+03,0.000000,1.655080e+03,918.000000,-40617.500000,2013-09-01 00:00:00,1.000000,2013.000000
25%,905.000000,5.000000,12.000000,1.739175e+04,800.320000,1.592800e+04,7490.000000,2805.960000,2013-12-24 06:00:00,5.750000,2013.750000
50%,1542.500000,10.000000,20.000000,3.798000e+04,2585.250000,3.554020e+04,22506.250000,9242.200000,2014-05-16 12:00:00,9.000000,2014.000000
75%,2229.125000,250.000000,300.000000,2.790250e+05,15956.343750,2.610775e+05,245607.500000,22662.000000,2014-09-08 12:00:00,10.250000,2014.000000
max,4492.500000,260.000000,350.000000,1.207500e+06,149677.500000,1.159200e+06,950625.000000,262200.000000,2014-12-01 00:00:00,12.000000,2014.000000
std,867.427859,108.602612,136.775515,2.542623e+05,22962.928775,2.367263e+05,203865.506118,42760.626563,NaN,3.377321,0.433322

In [ ]:
df["Country"].unique()

array(['Germany', 'Canada', 'France', 'Mexico',
       'United States of America'], dtype=object)

In [ ]:
df["Product"].unique()

array(['Carretera', 'Paseo', 'Velo', 'VTT', 'Amarilla', 'Montana'],
      dtype=object)

In [ ]:
df["Segment"].unique()

array(['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
       'Small Business'], dtype=object)

In [ ]:
df["Discount Band"].value_counts()

Discount Band
High       245
Medium     242
Low        160
Unknown     53
Name: count, dtype: int64

In [ ]:
print("Total Sales:", round(df["Sales"].sum(), 2))
print("Total Profit:", df["Profit"].sum())
print("Total Units Sold:", df["Units Sold"].sum())

Total Sales: 118726350.26
Total Profit: 16893702.26
Total Units Sold: 1125806.0

In [ ]:
df["Profit Margin"] = np.where(
    df["Sales"] != 0,
    df["Profit"] / df["Sales"],
    np.nan
)

In [ ]:
df[["Sales", "Profit", "Profit Margin"]].head()

      Sales    Profit  Profit Margin
0  529550.0  136170.0       0.257143
1  352100.0   90540.0       0.257143
2  603750.0  155250.0       0.257143
3  529550.0  136170.0       0.257143
4  352100.0   90540.0       0.257143

In [ ]:
df["Discount Rate"] = np.where(
    df["Gross Sales"] != 0,
    df["Discounts"] / df["Gross Sales"],
    np.nan
)

In [ ]:
df[["Gross Sales", "Discounts", "Discount Rate"]].head()

   Gross Sales  Discounts  Discount Rate
0     529550.0        0.0            0.0
1     352100.0        0.0            0.0
2     603750.0        0.0            0.0
3     529550.0        0.0            0.0
4     352100.0        0.0            0.0

In [ ]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year,Profit Margin,Discount Rate
0,Government,Germany,Carretera,Unknown,1513.0,3,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014,0.257143,0.0
1,Government,Germany,Paseo,Unknown,1006.0,10,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014,0.257143,0.0
2,Government,Canada,Paseo,Unknown,1725.0,10,350,603750.0,0.0,603750.0,448500.0,155250.0,2013-11-01,11,November,2013,0.257143,0.0
3,Government,Germany,Paseo,Unknown,1513.0,10,350,529550.0,0.0,529550.0,393380.0,136170.0,2014-12-01,12,December,2014,0.257143,0.0
4,Government,Germany,Velo,Unknown,1006.0,120,350,352100.0,0.0,352100.0,261560.0,90540.0,2014-06-01,6,June,2014,0.257143,0.0

In [ ]:
# df.to_excel("Capstone_Cleaned_Data.xlsx", index=False)

In [ ]:
# Analyze data using SQL or Pandas.

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_units = df["Units Sold"].sum()
total_gross_sales = df["Gross Sales"].sum()
total_discounts = df["Discounts"].sum()
total_cogs = df["COGS"].sum()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Units Sold:", total_units)
print("Total Gross Sales:", total_gross_sales)
print("Total Discounts:", total_discounts)
print("Total COGS:", total_cogs)

Total Sales: 118726350.25999999
Total Profit: 16893702.26
Total Units Sold: 1125806.0
Total Gross Sales: 127931598.5
Total Discounts: 9205248.239999998
Total COGS: 101832648.0

In [ ]:
profit_margin = total_profit / total_sales

print("Overall Profit Margin:", round(profit_margin, 2))

Overall Profit Margin: 0.14

In [ ]:
discount_rate = total_discounts / total_gross_sales

print("Overall Discount Rate:", round(discount_rate, 2))

Overall Discount Rate: 0.07

In [ ]:
country_analysis = df.groupby("Country").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units_Sold=("Units Sold", "sum")
).reset_index()

country_analysis

                    Country         Sales       Profit  Units_Sold
0                    Canada  2.488765e+07  3529228.885    247428.5
1                    France  2.435417e+07  3781020.780    240931.0
2                   Germany  2.350534e+07  3680388.820    201494.0
3                    Mexico  2.094935e+07  2907523.110    203325.0
4  United States of America  2.502983e+07  2995540.665    232627.5

In [ ]:
country_analysis.sort_values(
    by="Sales",
    ascending=False
)

                    Country         Sales       Profit  Units_Sold
4  United States of America  2.502983e+07  2995540.665    232627.5
0                    Canada  2.488765e+07  3529228.885    247428.5
1                    France  2.435417e+07  3781020.780    240931.0
2                   Germany  2.350534e+07  3680388.820    201494.0
3                    Mexico  2.094935e+07  2907523.110    203325.0

In [ ]:
country_analysis.sort_values(
    by="Profit",
    ascending=False
)

                    Country         Sales       Profit  Units_Sold
1                    France  2.435417e+07  3781020.780    240931.0
2                   Germany  2.350534e+07  3680388.820    201494.0
0                    Canada  2.488765e+07  3529228.885    247428.5
4  United States of America  2.502983e+07  2995540.665    232627.5
3                    Mexico  2.094935e+07  2907523.110    203325.0

In [ ]:
country_analysis["Profit Margin"] = (
    country_analysis["Profit"] /
    country_analysis["Sales"]
)

In [ ]:
country_analysis.sort_values(
    by="Profit Margin",
    ascending=False
)

,Country,Sales,Profit,Units_Sold,Profit Margin
2,Germany,2.350534e+07,3680388.820,201494.0,0.156577
1,France,2.435417e+07,3781020.780,240931.0,0.155251
0,Canada,2.488765e+07,3529228.885,247428.5,0.141806
3,Mexico,2.094935e+07,2907523.110,203325.0,0.138788
4,United States of America,2.502983e+07,2995540.665,232627.5,0.119679

In [ ]:
product_analysis = df.groupby("Product").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units_Sold=("Units Sold", "sum")
).reset_index()

product_analysis

     Product         Sales       Profit  Units_Sold
0   Amarilla  1.774712e+07  2814104.060    155315.0
1  Carretera  1.381531e+07  1826804.885    146846.0
2    Montana  1.539080e+07  2114754.880    154198.0
3      Paseo  3.301114e+07  4797437.950    338239.5
4        VTT  2.051192e+07  3034608.020    168783.0
5       Velo  1.825006e+07  2305992.465    162424.5

In [ ]:
product_analysis.sort_values(
    by="Sales",
    ascending=False
)

     Product         Sales       Profit  Units_Sold
3      Paseo  3.301114e+07  4797437.950    338239.5
4        VTT  2.051192e+07  3034608.020    168783.0
5       Velo  1.825006e+07  2305992.465    162424.5
0   Amarilla  1.774712e+07  2814104.060    155315.0
2    Montana  1.539080e+07  2114754.880    154198.0
1  Carretera  1.381531e+07  1826804.885    146846.0

In [ ]:
product_analysis.sort_values(
    by="Profit",
    ascending=False
)

     Product         Sales       Profit  Units_Sold
3      Paseo  3.301114e+07  4797437.950    338239.5
4        VTT  2.051192e+07  3034608.020    168783.0
0   Amarilla  1.774712e+07  2814104.060    155315.0
5       Velo  1.825006e+07  2305992.465    162424.5
2    Montana  1.539080e+07  2114754.880    154198.0
1  Carretera  1.381531e+07  1826804.885    146846.0

In [ ]:
product_analysis["Profit Margin"] = (
    product_analysis["Profit"] /
    product_analysis["Sales"]
)

In [ ]:
product_analysis.sort_values(
    by="Profit Margin",
    ascending=False
)

     Product         Sales       Profit  Units_Sold  Profit Margin
0   Amarilla  1.774712e+07  2814104.060    155315.0       0.158567
4        VTT  2.051192e+07  3034608.020    168783.0       0.147944
3      Paseo  3.301114e+07  4797437.950    338239.5       0.145328
2    Montana  1.539080e+07  2114754.880    154198.0       0.137404
1  Carretera  1.381531e+07  1826804.885    146846.0       0.132230
5       Velo  1.825006e+07  2305992.465    162424.5       0.126355

In [ ]:
segment_analysis = df.groupby("Segment").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units_Sold=("Units Sold", "sum")
).reset_index()

segment_analysis

            Segment         Sales        Profit  Units_Sold
0  Channel Partners  1.800594e+06  1.316803e+06    161263.5
1        Enterprise  1.961169e+07 -6.145456e+05    168552.0
2        Government  5.250426e+07  1.138817e+07    470673.5
3         Midmarket  2.381883e+06  6.601031e+05    172178.0
4    Small Business  4.242792e+07  4.143168e+06    153139.0

In [ ]:
segment_analysis.sort_values(
    by="Sales",
    ascending=False
)

            Segment         Sales        Profit  Units_Sold
2        Government  5.250426e+07  1.138817e+07    470673.5
4    Small Business  4.242792e+07  4.143168e+06    153139.0
1        Enterprise  1.961169e+07 -6.145456e+05    168552.0
3         Midmarket  2.381883e+06  6.601031e+05    172178.0
0  Channel Partners  1.800594e+06  1.316803e+06    161263.5

In [ ]:
segment_analysis.sort_values(
    by="Profit",
    ascending=False
)

            Segment         Sales        Profit  Units_Sold
2        Government  5.250426e+07  1.138817e+07    470673.5
4    Small Business  4.242792e+07  4.143168e+06    153139.0
0  Channel Partners  1.800594e+06  1.316803e+06    161263.5
3         Midmarket  2.381883e+06  6.601031e+05    172178.0
1        Enterprise  1.961169e+07 -6.145456e+05    168552.0

In [ ]:
segment_analysis[segment_analysis["Profit"] < 0]

      Segment         Sales      Profit  Units_Sold
1  Enterprise  1.961169e+07 -614545.625    168552.0

In [ ]:
year_analysis = df.groupby("Year").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Units_Sold=("Units Sold", "sum")
).reset_index()

year_analysis

   Year        Sales       Profit  Units_Sold
0  2013  26415255.51   3878464.51    264674.0
1  2014  92311094.75  13015237.75    861132.0

In [ ]:
year_analysis["Profit Margin"] = (
    year_analysis["Profit"] /
    year_analysis["Sales"]
)

In [ ]:
sales_growth = (
    (year_analysis["Sales"].iloc[-1] -
     year_analysis["Sales"].iloc[0])
    / year_analysis["Sales"].iloc[0]
) * 100

print("Sales Growth (%):", sales_growth)

Sales Growth (%): 249.46129790436387

In [ ]:
profit_growth = (
    (year_analysis["Profit"].iloc[-1] -
     year_analysis["Profit"].iloc[0])
    / year_analysis["Profit"].iloc[0]
) * 100

print("Profit Growth (%):", profit_growth)

Profit Growth (%): 235.57707480479175

In [ ]:
discount_analysis = df.groupby("Discount Band").agg(
    Sales=("Sales", "sum"),
    Discounts=("Discounts", "sum"),
    Profit=("Profit", "sum")
).reset_index()

discount_analysis

  Discount Band         Sales    Discounts       Profit
0          High  3.737249e+07  5317026.275  3388866.725
1           Low  3.462978e+07   885675.800  6188857.700
2        Medium  3.878043e+07  3002546.165  5579522.835
3       Unknown  7.943654e+06        0.000  1736455.000

In [ ]:
discount_analysis["Profit Margin"] = (
    discount_analysis["Profit"] /
    discount_analysis["Sales"]
)

In [ ]:
discount_analysis.sort_values(
    by="Profit Margin",
    ascending=False
)

  Discount Band         Sales    Discounts       Profit  Profit Margin
3       Unknown  7.943654e+06        0.000  1736455.000       0.218597
1           Low  3.462978e+07   885675.800  6188857.700       0.178715
2        Medium  3.878043e+07  3002546.165  5579522.835       0.143875
0          High  3.737249e+07  5317026.275  3388866.725       0.090678

In [ ]:
top_products = product_analysis.sort_values(
    by="Sales",
    ascending=False
).head(5)

top_products

    Product         Sales       Profit  Units_Sold  Profit Margin
3     Paseo  3.301114e+07  4797437.950    338239.5       0.145328
4       VTT  2.051192e+07  3034608.020    168783.0       0.147944
5      Velo  1.825006e+07  2305992.465    162424.5       0.126355
0  Amarilla  1.774712e+07  2814104.060    155315.0       0.158567
2   Montana  1.539080e+07  2114754.880    154198.0       0.137404

In [ ]:
bottom_products = product_analysis.sort_values(
    by="Sales",
    ascending=True
).head(5)

bottom_products

     Product         Sales       Profit  Units_Sold  Profit Margin
1  Carretera  1.381531e+07  1826804.885    146846.0       0.132230
2    Montana  1.539080e+07  2114754.880    154198.0       0.137404
0   Amarilla  1.774712e+07  2814104.060    155315.0       0.158567
5       Velo  1.825006e+07  2305992.465    162424.5       0.126355
4        VTT  2.051192e+07  3034608.020    168783.0       0.147944

In [ ]:
best_country = country_analysis.loc[
    country_analysis["Profit"].idxmax()
]

best_country

Country               France
Sales            24354172.28
Profit            3781020.78
Units_Sold          240931.0
Profit Margin       0.155251
Name: 1, dtype: object

In [ ]:
worst_country = country_analysis.loc[
    country_analysis["Profit"].idxmin()
]

worst_country

Country               Mexico
Sales            20949352.11
Profit            2907523.11
Units_Sold          203325.0
Profit Margin       0.138788
Name: 3, dtype: object

In [ ]:
best_product = product_analysis.loc[
    product_analysis["Profit"].idxmax()
]

best_product

Product                Paseo
Sales            33011143.95
Profit            4797437.95
Units_Sold          338239.5
Profit Margin       0.145328
Name: 3, dtype: object

In [ ]:
worst_product = product_analysis.loc[
    product_analysis["Profit"].idxmin()
]

worst_product

Product             Carretera
Sales            13815307.885
Profit            1826804.885
Units_Sold           146846.0
Profit Margin         0.13223
Name: 1, dtype: object